# Generated by Django 6.0 on 2025-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_create_packing_list",
            field=models.BooleanField(
                default=False, verbose_name="Can Create Packing List"
            ),
        ),
    ]
