# Generated by Django 6.0 on 2025-12-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = []
