# Generated by Django 6.0 on 2025-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_shipment_routehistory_shipmentstatusupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="tracking_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
