# Generated by Django 6.0 on 2025-12-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0004_alter_shipment_tracking_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentstatusupdate",
            name="shipment",
        ),
        migrations.RemoveField(
            model_name="shipmentstatusupdate",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="RouteHistory",
        ),
        migrations.DeleteModel(
            name="ShipmentStatusUpdate",
        ),
    ]
