# Generated by Django 6.0 on 2025-12-15 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0005_remove_shipmentstatusupdate_shipment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_cartons", models.IntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pdf_file",
                    models.FileField(max_length=500, upload_to="packing_lists/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Packing List",
                "verbose_name_plural": "Packing Lists",
                "ordering": ["-created_at"],
            },
        ),
    ]
