# Generated by Django 6.0 on 2025-12-16 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0006_packinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglist",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
