# Generated by Django 6.0 on 2025-12-16 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0007_packinglist_unique_id_alter_packinglist_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packinglist",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
