# Generated by Django 6.0 on 2025-12-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0008_alter_packinglist_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packinglist",
            name="code",
        ),
    ]
